### ISSUE TITLE
Sequential if vs. else if

### ISSUE THREAD

**Issue by tamberg** [arduino/EduIntro#1]
Is there a reason you use sequential _if_ statements, instead of _else if_? E.g. in

https://github.com/arduino/EduIntro/blob/master/examples/by_topic/PhysicalPixel/PhysicalPixel.ino#L44

Kind regards,
Thomas

**Comment by dcuartielles** [comment]
Not really. This is one of the original examples from the Arduino IDE from 2005 and we have just adjusted it to fit this library. Technically we are only checking in byte at the time, what makes impossible to have the byte to enter more than one of the if statements, unless you modify the variable in your own code.

I will close this issue as it is not something we will change. However, it is interesting considering an example where else if (as well as other conditionals like switch case) would make sense. Feel free to suggest one.
